### PR TITLE
Fix resolve dependee

### LINKED ISSUE #9: resolveDependee `obj` is always `rootValue`
Hi, I am having some trouble with resolveDependee, this function call the dependant resolver but not with the right object as first argument but the rootValue of my schema.

### PR DESCRIPTION
**Pull request by nchaulet**
Attempt to fix #9 

I am sure we can write with a more functional approach.

### CODE REVIEW

**Comment by nchaulet** [comment]
@lucasconstantino any chance you look at this?

**Comment by lucasconstantino** [comment]
@nchaulet not today nor tomorrow, but by the end of the week I'll have time to review this. Sorry for the delay.

**Comment by nchaulet** [comment]
No problem, thanks for the answer

**Comment by ihoka** [comment]
I can confirm this fixes #9 for me.

**Comment by lucasconstantino** [comment]
Thanks, @ihoka! Sorry for the delay guys, new release 0.3.3 is out.

**Pull request merged**
